spring:
  application:
    name: discord-bot-initializer

server:
  port: 3030
  error:
    include-message: always
    include-binding-errors: always



logging:
  level:
    root: INFO
    org.springframework: INFO
    Grad_Project.Discord_Bot_Initializer.controller: DEBUG